### PR TITLE
[ECH-625]: Add GTH and XLA icons, fix APT icon

### PR DESCRIPTION
**Pull request by anhan32**
Linear tickets:

- [ECH-625](https://linear.app/unstoppable-domains/issue/ECH-625/new-currency-support-gather-gth)
- [ECH-564](https://linear.app/unstoppable-domains/issue/ECH-564/new-currency-support-xla)
- [ECH-552](https://linear.app/unstoppable-domains/issue/ECH-552/new-currency-support-apt)

Icons - Crypto Icons ⋅ Storybook 2023-01-17 14-35-17

Icons - Crypto Icons ⋅ Storybook 2023-01-17 14-36-29

Icons - Crypto Icons ⋅ Storybook 2023-01-17 14-54-28

### CODE REVIEW

**Review by dgrishajev — APPROVED** [review]
Looks good, thanks!

**Review by sudoryan — APPROVED** [review]

**Review by iurevych — CHANGES_REQUESTED** [review]
All crypto icons must be rectangular

**Comment by iurevych** [comment]
You can ask Daniil for an icon

**Review by iurevych — APPROVED** [review]
✨

**Pull request merged**
